karma/karma/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('ru/', include('mainapp.urls_ru', namespace='mainapp_ru')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

karma/mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.index, name='index'),
]

karma/mainapp/models.py
from django.db import models

# Create your models here.

karma/mainapp/views.py
from django.shortcuts import render


def index(request):
    if '/ru/' in request.path:
        template = 'mainapp/index_ru.html'
    else:
        template = 'mainapp/index.html'
    return render(request, template)

karma/mainapp/templates/mainapp/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
        <title>Karma - Main</title>
    </head>
    <body>
        <h1>Karma - Main</h1>
        <a href="/admin">Admin</a>
        <a href="{% url 'mainapp_ru:index' %}">RU</a>
    </body>
</html>

karma/mainapp/templates/mainapp/index_ru.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
        <title>Karma - Главная</title>
    </head>
    <body>
        <h1>Karma - Главная</h1>
        <a href="/admin">Админка</a>
        <a href="{% url 'mainapp:index' %}">Англ</a>
    </body>
</html>